# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Suraj Verma
tagline:          Engineering
description:      Software Engineer | Learning stuff...
url:              https://surajv311.github.io
baseurl:          ""

author:
  name:           'Suraj Verma'
  url:            https://in.linkedin.com/in/surajverma-sv

paginate:         5

# Custom vars
version:          1.0.18

github:
  repo:           https://github.com/Surajv311/surajv311.github.io

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
